In [172]:
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import MinMaxScaler
from sklearn import tree
from sklearn import linear_model


file = "train.csv"
data = pd.read_csv(file)
data['hh_totalmembers'].describe()
data = data.drop('surveyid', axis=1)
data = data.drop('survey_date', axis=1)


n_records = data.shape[0]
n_depressed = data['depressed'].value_counts()[1]

print("Total number of records: {}".format(n_records))
print("Total number of people depressed: {}".format(n_depressed))

Total number of records: 1143
Total number of people depressed: 193

In [173]:
## Making categorical variables into one-hot vector
cat_variables = ['village','femaleres','married','labor_primary','day_of_week']

one_hot = pd.get_dummies(data, columns = cat_variables)
one_hot.head(n=5)

var_names = list(one_hot) #keeping track of variable names

In [174]:
## Taking out variables that have more than 500 missing values
listy = one_hot.isnull().sum()
names = list(listy.index)
to_take_out = []
for element in names:
    if listy[element] >=500:
        to_take_out.append(element)
one_hot = one_hot.drop(to_take_out, axis=1)

In [175]:
#Changing variables with less than 200 into their most frequent value

listy = one_hot.isnull().sum()
names = list(listy.index)
few_missing = []
for element in names:
    if listy[element] > 0 and listy[element] <200:
        few_missing.append(element)


imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp.fit(one_hot[few_missing])
one_hot[few_missing]= imp.transform(one_hot[few_missing])
one_hot = pd.DataFrame(one_hot)

In [176]:
listy = one_hot.isnull().sum()
names = list(listy.index)
missing = []
for element in names:
    if listy[element] > 0:
        missing.append(element)
missing

['hh_totalmembers',
 'cons_med_children',
 'fs_chskipm_often',
 'fs_chwholed_often',
 'fs_meat',
 'fs_enoughtom',
 'fs_sleephun',
 'med_portion_sickinjured',
 'med_port_sick_child',
 'med_afford_port',
 'med_sickdays_hhave',
 'med_healthconsult',
 'ed_expenses',
 'ed_expenses_perkid',
 'ed_schoolattend',
 'ed_sch_missedpc']

In [177]:
var_names = list(one_hot)
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp.fit(one_hot)
temp_data = imp.transform(one_hot)
temp_data = pd.DataFrame(temp_data)
temp_data.columns = var_names

X = temp_data.drop('hh_totalmembers',axis = 1)
y = temp_data['hh_totalmembers']
lm = linear_model.LinearRegression()
new_y = lm.fit(X,y).predict(X)

In [188]:
one_hot_copy = one_hot.copy()


for variable in missing:
    X = temp_data.drop(variable,axis = 1)
    y = temp_data[variable]
    lm = linear_model.LinearRegression()
    new_y = lm.fit(X,y).predict(X)
    for value in range(1143):
        if one_hot[variable][value]!= one_hot[variable][value]:
            one_hot_copy[variable][value] = new_y[value]

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [190]:
one_hot_copy.isnull().sum()

age                       0
children                  0
hhsize                    0
edu                       0
hh_children               0
hh_totalmembers           0
cons_nondurable           0
asset_livestock           0
asset_durable             0
asset_phone               0
asset_savings             0
asset_land_owned_total    0
asset_niceroof            0
cons_allfood              0
cons_ownfood              0
cons_alcohol              0
cons_tobacco              0
cons_med_total            0
cons_med_children         0
cons_ed                   0
cons_social               0
cons_other                0
ent_wagelabor             0
ent_ownfarm               0
ent_business              0
ent_nonagbusiness         0
ent_employees             0
ent_nonag_revenue         0
ent_nonag_flowcost        0
ent_farmrevenue           0
                         ..
village_258               0
village_260               0
village_262               0
village_263               0
village_264               0
village_265               0
village_266               0
village_267               0
village_269               0
village_275               0
village_278               0
village_281               0
village_283               0
village_285               0
village_287               0
village_290               0
village_292               0
femaleres_0               0
femaleres_1               0
married_0                 0
married_1                 0
labor_primary_0           0
labor_primary_1           0
day_of_week_0             0
day_of_week_1             0
day_of_week_2             0
day_of_week_3             0
day_of_week_4             0
day_of_week_5             0
day_of_week_6             0
Length: 317, dtype: int64

In [203]:
## Scaling values
scaler = MinMaxScaler()
var_names = list(one_hot_copy)
train = scaler.fit_transform(one_hot_copy)
train = pd.DataFrame(train)
train.columns = var_names
display(train.head(n = 5))

X_train = train.drop('depressed', axis=1)
Y_train = train['depressed']


data = pd.read_csv('test.csv')
data = data.drop('surveyid', axis=1)
data = data.drop('survey_date', axis=1)
data['age'] = data['age'].replace({'.d':np.nan})


data = data.drop(to_take_out, axis=1)
one_hot = pd.get_dummies(data, columns = cat_variables)
var_names = list(one_hot) #keeping track of variable names
## Imputing missing values
imp = Imputer(missing_values='NaN', strategy='most_frequent', axis=0)
imp.fit(one_hot)
one_hot= imp.transform(one_hot)
test = pd.DataFrame(one_hot)
## Scaling values
scaler = MinMaxScaler()
test = scaler.fit_transform(test)
test = pd.DataFrame(test)
test.columns = var_names
Y_test = test['depressed']
X_test = test.drop('depressed', axis=1)


train_list = list(X_train)
test_list = list(X_test)
listy = []
for element in train_list:
    if element not in test_list:
        listy.append(element)
        X_test[element] = 0

        
for element in test_list:
    if element not in train_list:
        listy.append(element)
        X_train[element] = 0


        
clf = tree.DecisionTreeClassifier(min_samples_leaf=16)


clf.fit(X_train, Y_train)
clf.score(X_test,Y_test)

Y_predicted = clf.predict(X_test)

tots = 0
for i in range(len(Y_test)):
    if Y_predicted[i] != Y_test[i]:
        tots +=1
print("The percentage of predictions that are not the same is {:.2f}%".format(tots/len(Y_predicted)*100))



ids = pd.read_csv('test.csv')
ids = ids['surveyid']
ids = pd.DataFrame(ids)
Y_predicted = pd.DataFrame(Y_predicted)
Y_predicted.columns = ['depressed']

sub = pd.merge(ids,Y_predicted,left_index =True,right_index=True)

sub['depressed'] = sub['depressed'].astype(int)
sub.to_csv('andres_parrado_submission6.csv', encoding='utf-8')

,age,children,hhsize,edu,hh_children,hh_totalmembers,cons_nondurable,asset_livestock,asset_durable,asset_phone,...,married_1,labor_primary_0,labor_primary_1,day_of_week_0,day_of_week_1,day_of_week_2,day_of_week_3,day_of_week_4,day_of_week_5,day_of_week_6
0,0.148649,0.4,0.454545,0.500000,0.0,0.252208,0.000000,0.000000,0.000000,0.000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.081081,0.3,0.363636,0.388889,0.0,0.282601,0.000000,0.000000,0.000000,0.000,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.067568,0.3,0.363636,0.444444,0.0,0.248678,0.000000,0.000000,0.000000,0.000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.135135,0.2,0.272727,0.500000,0.2,0.272727,0.264620,0.191202,0.052949,0.125,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.567568,0.4,0.454545,0.500000,0.4,0.454545,0.180686,0.002999,0.046642,0.100,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

The percentage of predictions that are not the same is 12.24%

In [198]:
data

,village,femaleres,age,married,children,hhsize,edu,hh_children,hh_totalmembers,cons_nondurable,...,given_mpesa,amount_given_mpesa,received_mpesa,amount_received_mpesa,net_mpesa,saved_mpesa,amount_saved_mpesa,early_survey,depressed,day_of_week
0,181,1,21,0,3,4,10,3,4.0,357.817690,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,0.0,3
1,47,1,44,1,6,8,6,6,8.0,233.441540,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,0.0,2
2,8,1,23,1,1,3,7,1,3.0,171.970760,...,0,0.0,0,0.000000,0.000000,1,0.080077,0,0.0,1
3,25,1,67,0,0,1,1,0,1.0,37.013428,...,0,0.0,0,0.000000,0.000000,0,0.000000,1,1.0,3
4,2,1,40,1,4,6,7,4,6.0,156.061390,...,0,0.0,0,0.000000,0.000000,0,0.000000,1,NaN,4
5,15,1,54.700001,1,2,4,4,2,4.0,180.020000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
6,52,1,25,1,6,8,6,6,8.0,129.665390,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,1
7,28,1,43,0,6,8,9,6,8.0,246.229060,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
8,279,1,23,1,2,4,9,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,9.609222,0,NaN,4
9,96,1,22,1,2,4,7,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,1
10,164,1,31,1,3,5,10,3,5.0,323.054780,...,0,0.0,1,4.804611,4.804611,1,0.000000,0,NaN,4
11,104,1,68,1,1,3,4,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
12,256,1,28,1,2,4,10,2,4.0,73.774040,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,1
13,29,1,49,1,3,5,9,3,5.0,104.317630,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
14,187,1,79,1,0,2,12,0,2.0,73.277939,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
15,133,1,47,0,3,5,7,3,5.0,150.346940,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
16,38,1,58,0,2,4,8,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
17,39,1,21,1,2,4,10,2,4.0,66.058067,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
18,48,1,67,1,0,3,8,0,3.0,186.151600,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
19,76,1,26,0,3,4,10,3,4.0,201.684600,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
20,4,0,33,0,3,5,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
21,218,1,38,1,11,13,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,4
22,44,1,26,1,3,5,10,3,5.0,108.401180,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
23,166,1,25,1,2,4,9,2,4.0,254.667250,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,4
24,87,1,26,1,4,6,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,5
25,78,0,40,1,0,2,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
26,149,1,24,1,3,5,8,3,5.0,175.200520,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,0
27,45,1,24,1,5,7,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
28,79,1,33,1,7,9,7,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
29,29,1,73,1,2,5,12,2,5.0,199.761230,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,27,1,26,1,3,5,9,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,5
257,23,1,26,1,1,3,9,1,3.0,107.160750,...,0,0.0,1,8.007685,8.007685,0,0.000000,0,NaN,5
258,5,0,41,0,3,4,10,3,4.0,255.474730,...,0,0.0,0,0.000000,0.000000,1,48.046108,0,NaN,0
259,136,1,20,1,1,3,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
260,81,1,36,0,0,3,10,0,3.0,49.861183,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
261,88,1,25.299999,1,2,4,10,2,4.0,150.365630,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
262,222,1,21,1,3,5,10,3,5.0,173.382770,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
263,17,1,49,1,5,11,9,5,11.0,144.075410,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,6
264,12,1,59,0,0,3,7,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
265,36,1,59,1,5,7,12,5,7.0,257.797880,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
266,53,1,33,1,4,6,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
267,57,1,36,1,5,8,10,5,8.0,109.892130,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,3
268,6,1,41,1,5,9,9,5,9.0,200.745040,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,4
269,89,1,25,1,1,3,9,1,3.0,26.009724,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,2
270,37,1,36,1,6,8,14,6,8.0,207.252240,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
271,104,1,72,1,0,3,9,0,3.0,80.946251,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,2
272,93,1,34,1,3,5,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,5
273,46,1,44,1,5,10,1,0,NaN,0.000000,...,0,0.0,1,24.023054,24.023054,0,0.000000,0,NaN,2
274,7,1,21,1,1,3,10,1,3.0,153.430680,...,0,0.0,0,0.000000,0.000000,1,56.053795,0,NaN,6
275,192,1,25,1,3,5,8,3,5.0,154.773300,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
276,7,1,30,1,1,3,14,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,2.402306,0,NaN,3
277,52,1,20,1,2,4,10,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,4
278,188,1,20,1,2,4,10,2,4.0,187.175840,...,0,0.0,1,24.023054,24.023054,0,0.000000,0,NaN,6
279,27,1,35,1,6,8,6,6,8.0,144.083790,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
280,15,1,25,1,3,5,9,3,5.0,425.076510,...,0,0.0,1,24.023054,24.023054,0,0.000000,0,NaN,4
281,22,1,25,1,1,3,7,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,1
282,69,1,28,1,4,6,10,4,6.0,248.608690,...,0,0.0,0,0.000000,0.000000,1,0.000000,0,NaN,5
283,184,1,66,0,0,1,1,0,1.0,28.416222,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
284,75,1,51,1,1,3,12,0,NaN,0.000000,...,0,0.0,0,0.000000,0.000000,0,0.000000,0,NaN,3
285,12,1,33,0,4,5,8,4,5.0,512.779360,...,0,0.0,1,8.007685,8.007685,0,0.000000,0,NaN,6